name: Broadcast every 30 minutes
on:
  schedule:
    - cron: "1,31 * * * *"
jobs:
  webhook:
    name: Ping webhook
    runs-on: ubuntu-latest
    steps:
      - name: ping webhook
        run: |
          curl -X GET "https://octorates.tomd.org/api/broadcast"
