name: Broadcast every 30 minutes
on:
  schedule:
    - cron: "1,31 * * * *"
jobs:
  webhook:
    name: Ping webhook
    runs-on: ubuntu-latest
    steps:
      - name: Use webhook action to ping webhook
        uses: joelwmale/webhook-action@2.3.2
        with:
          url: https://octorates.tomd.org/api/broadcast
